INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('AP ACOMPA—AMIENTO INGENIERIA',null,'IP14ACING','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('AP AN¡LISIS DE SISTEMAS ESTRUCTURALES',null,'IP14ASE','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('AP MEC¡ÅNICA DE S”LIDOS RÕçGIDOS',null,'IP14MSR','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('AP PROBABILIDAD Y ESTADÕçSTICA',null,'IP14PYE','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('BANCO DE ARCHIVOS DIGITALES ARTE',null,'IP14BAD','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('SISTEMA DE CASOS CLINICOS',null,'IP14SCC','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('PSICOLOGÕçA DEL DESARROLLO',null,'IP14SIDE','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('AIEPI',null,'IP14AIEPI','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('FORTALECIMIENTO MODELO EDUCATIVO CONSULTANDES',null,'IP15CON','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('EPIS-FARMA',null,'IP15FAR','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('PROCESOS DE APRENDIZAJE EN FEN”MENOS DE TRANSPORTE',null,'IP15FET','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('GEOC-SENSE',null,'IP15GEO','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('CURSO GAS, CARB”N Y PETROLEO',null,'IP15GPC','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('PROSODIA-M¡S ALL¡ DE LA PRONUNCIACI”N',null,'IP15ING6','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('MEMORIZACI”N O COMPRENSI”N',null,'IP15INMU','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('ADHERENCIA A ESTILOS DE VIDA SALUDABLE',null,'IP15VIDA','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('CBU CONSTRUCTIVISMO Y APRENDIZAJE',null,'IP15CYA','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('ORION',null,'IP15ORI','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('METODOLOGÕçA PENSAMIENTO DE DISE—O',null,'IP15TIN','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('MATEMATICAS',null,'IP13MAT','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('…TICA PARA LA INVESTIGACI”N',null,'PO16EINV','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('MECANISMOS ALTERNATIVOS DE SOLUCI”N DE CONFLICTOS',null,'IP16MASC','01/01/2019','31/12/2019');
INSERT INTO public.sisred_app_proyectoconectate(nombre, nombre_corto, codigo, fecha_inicio, fecha_fin) VALUES ('MAESTRÕA EN GERENCIA AMBIENTAL - MGA. CONFLICTOS',null,'PO15CONF','01/01/2019','31/12/2019');
