# Generated by Django 2.1.5 on 2019-03-30 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conectate', models.CharField(max_length=50)),
                ('nombre_fase', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('numero_identificacion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=200)),
                ('valor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoConectate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoRED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('carpeta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_ultima_modificacion', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_autor', to='sisred_app.Perfil')),
                ('metadata', models.ManyToManyField(to='sisred_app.Metadata')),
                ('usuario_ultima_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_ultima_modificacion', to='sisred_app.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('porcentaje_avance', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('solicitante', models.CharField(max_length=50)),
                ('horas_estimadas', models.IntegerField()),
                ('horas_trabajadas', models.IntegerField()),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisred_app.Fase')),
                ('metadata', models.ManyToManyField(to='sisred_app.Metadata')),
                ('proyecto_conectate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.ProyectoConectate')),
                ('recursos', models.ManyToManyField(to='sisred_app.Recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RolAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('notificaciones', models.ManyToManyField(to='sisred_app.Notificacion')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.RED')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='SubproductoRED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproductos_del_red', to='sisred_app.RED')),
                ('subproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reds_del_subproducto', to='sisred_app.RED')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_final', models.BooleanField(default=False)),
                ('numero', models.IntegerField()),
                ('archivo', models.CharField(max_length=200)),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.RED')),
            ],
        ),
        migrations.AddField(
            model_name='proyectored',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.RED'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Recurso'),
        ),
        migrations.AddField(
            model_name='historialestados',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.RED'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Recurso'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Version'),
        ),
    ]
