# Generated by Django 2.1.5 on 2019-04-11 04:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisred_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='archivo',
            new_name='archivos',
        ),
        migrations.AddField(
            model_name='version',
            name='creadoPor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sisred_app.Perfil'),
        ),
        migrations.AddField(
            model_name='version',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='imagen',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='recursos',
            field=models.ManyToManyField(blank=True, to='sisred_app.Recurso'),
        ),
    ]
