# Generated by Django 2.1.5 on 2019-04-26 03:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisred_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('y1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('x2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('y2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_ini', models.IntegerField(blank=True, null=True)),
                ('seg_fin', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rolasignado',
            name='notificaciones',
        ),
        migrations.AddField(
            model_name='comentario',
            name='cerrado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_sisred',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='red',
            name='listo_para_revision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.AddField(
            model_name='comentariomultimedia',
            name='comentario_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisred_app.ComentarioVideo'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_multimedia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sisred_app.ComentarioMultimedia'),
        ),
    ]
