# Generated by Django 2.1.5 on 2019-04-26 04:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisred_app', '0002_auto_20190426_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_notificacion', to='sisred_app.TipoNotificacion')),
            ],
        ),
        migrations.AddField(
            model_name='rolasignado',
            name='notificaciones',
            field=models.ManyToManyField(blank=True, to='sisred_app.Notificacion'),
        ),
    ]
